name: GoLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
        args:  --config=./.golangci.yml

    - name: Vet
      run: go vet ./...
